### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'n_warmup_steps'

### ISSUE THREAD

**Issue by vnlebaoduy** [pbcquoc/vietocr#10]
Em nhận được thông báo này khi training ạ. Mong anh chỉ dẫn cách fix lỗi này ạ
```
Computing MD5: /tmp/tranformerorc.pth
MD5 matches: /tmp/tranformerorc.pth
transformer.embed_tgt.weight missmatching shape
transformer.fc.weight missmatching shape
transformer.fc.bias missmatching shape
Traceback (most recent call last):
  File "main.py", line 26, in <module>
    trainer = Trainer(config, pretrained=True)
  File "/Volumes/DATA/DRAF/Deep Learning/DetectHand2/vietocr/model/trainer.py", line 62, in __init__
    self.scheduler = OneCycleLR(self.optimizer, **config['optimizer'])
TypeError: __init__() got an unexpected keyword argument 'n_warmup_steps'
```

Dưới dây là code của em:
```python
from vietocr.tool.config import Cfg
from vietocr.model.trainer import Trainer


if __name__ == '__main__':
    config = Cfg.load_config_from_name('vgg_transformer')
    dataset_params = {
        'name': 'hw',
        'data_root': './data/',
        'train_annotation': 'train_annotation.txt',
        'valid_annotation': 'test_annotation.txt'
    }

    params = {
        'print_every': 200,
        'valid_every': 15 * 200,
        'iters': 20000,
        'checkpoint': './checkpoint/transformerocr_checkpoint.pth',
        'export': './weights/transformerocr.pth',
        'metrics': 10000
    }

    config['trainer'].update(params)
    config['dataset'].update(dataset_params)

    trainer = Trainer(config, pretrained=True)
    trainer.visualize_dataset()
```

**Comment by pbcquoc** [comment]
pip install vietocr==0.1.9
install version này e nhé.

**Comment by vnlebaoduy** [comment]
Đã sửa được lỗi rồi ạ. Em cảm ơn anh ạ.

**Comment by monotuko** [comment]
@vnlebaoduy bạn train ra file weights xong predict kết quả ra đúng không vậy?

**Comment by vnlebaoduy** [comment]
@monotuko Có 2 trường hợp mình xử lý:
1. chưa xử lý ảnh - viết nắn nót đều tay: Kết quả chính xác khá cao. VD như ảnh này
![Screen Shot 2020-10-06 at 18 15 40](https://user-images.githubusercontent.com/4734934/95194947-1b8a4200-0800-11eb-9160-84d4077af7be.png)

2. Mặc dù mình đã xử lý các khoảng trắng thừa, và xoá mờ gạch chân nhưng hiện tại vẫn chưa nhận dạng đúng - viết nhanh- thì hiện tại  chưa nhận dạng chính xác được. Và đây là ảnh ko nhận dạng được.
![119934736_1600955396742277_3398767390349532659_n](https://user-images.githubusercontent.com/4734934/95195103-4a081d00-0800-11eb-8f01-8ca1bb8ae2fe.jpg)
![119939709_2782889688667045_257501837782742806_n](https://user-images.githubusercontent.com/4734934/95195108-4b394a00-0800-11eb-8fd7-48dea54235c9.jpg)
![119947806_1013375229126415_881154671179369664_n](https://user-images.githubusercontent.com/4734934/95195110-4bd1e080-0800-11eb-8f6a-bf1609d5328f.jpg)
![120030148_344232276692970_6151809926057180962_n](https://user-images.githubusercontent.com/4734934/95195114-4c6a7700-0800-11eb-92fd-b87ea081be87.jpg)

Anh @pbcquoc có thể cho em xin lời khuyên để tăng độ chính xác lên được ko ạ. Em cảm ơn anh

**Comment by monotuko** [comment]
@vnlebaoduy bạn cho mình xin file cách train được không, mình train lại mà dùng file weights mới predict chữ đánh máy thì ra sai hết.
![image](https://user-images.githubusercontent.com/72443171/95202834-0e735000-080c-11eb-9683-617debe81f05.png)

**Comment by vnlebaoduy** [comment]
@monotuko  mình thấy bạn chữ nghe vẻ chưa được xử lý, độ phân giải còn khác thấp. Bạn nên preprocessing trước khi cho predict
