### ISSUE TITLE
Cannot pickle 'Environment' object

### ISSUE THREAD

**Issue by robindang0573** [pbcquoc/vietocr#101]
Cài đặt thư viện Vietocr trên Windows 10 và lựa chọn config['device'] = 'cpu' thì bị lỗi Cannot pickle 'Environment' object. Vui lòng đề xuất cách giải quyết. Cảm ơn nhiều.
![image](https://github.com/pbcquoc/vietocr/assets/30215462/5c6bd772-ead1-4a46-9276-40820c603a11)

**Comment by giangnv125** [comment]
@robindang0573 mình cũng gặp vấn đề tương tự, bạn đã giải quyết được chưa? Nếu rồi có thể giúp mình được không?

**Comment by droid2015** [comment]
Các bạn fix được chưa, tôi cũng bị lỗi 
![image](https://github.com/pbcquoc/vietocr/assets/10129599/0594a78b-9abc-40b7-b1be-95b13d4999b2)

**Comment by TamAIRC** [comment]
Bạn sửa config['dataloader']['num_workers'] = 0 và chạy lại
Bạn có thể xem lý do tại đây: https://discuss.pytorch.org/t/errors-when-using-num-workers-0-in-dataloader/97564/5

**Comment by droid2015** [comment]
OK cám ơn bạn
