### ISSUE TITLE
Can we train VietOCR model for Japanese language ? 

### ISSUE THREAD

**Issue by leviethung2103** [pbcquoc/vietocr#104]
Hi anh Việt,

Anh cho em hỏi em có thể sử dụng model VietOCR để training cho ngôn ngữ tiếng nhật được không ạ  ? Giả sử em đã có dataset tiếng Nhật rồi.

Nếu được thì em nên ứng dụng theo phương pháp nào ạ ? 
1. Sử dụng pretrained weight của model VietOCR để train lại
2. Train from scratch, không sử dụng pretrained weight ? 

Em cảm ơn ạ

**Comment by pbcquoc** [comment]
Hi e, 
e sử dunnjg pretrained weight sẽ tốt hơn.

**Comment by leviethung2103** [comment]
Dạ em cảm ơn anh ạ.
