### ISSUE TITLE
AttributeError: 'Delaunay' object has no attribute 'vertices'

### ISSUE THREAD

**Issue by twice1st** [pbcquoc/vietocr#105]
hi anh, cho em hỏi fix lỗi này trên colab sao ạ?
![image](https://github.com/pbcquoc/vietocr/assets/80203027/b8fb1ae3-73bb-4adf-9119-9fceeb217358)

**Comment by pbcquoc** [comment]
update thư viện này e nhé. 

pip install -U scikit-image

**Comment by twice1st** [comment]
kết quả vẫn bị lỗi anh ơi
![image](https://github.com/pbcquoc/vietocr/assets/80203027/abbeaed8-5f4e-430e-9dba-16f4ef56d823)

**Comment by pbcquoc** [comment]
pip install -U scikit-image 
chạy lệnh này trên colab trước kia chạy các cell khác e nhé.

**Comment by twice1st** [comment]
Dạ vâng, em cảm ơn anh ạ !!!
