### ISSUE TITLE
Có vấn đề khi sử dụng batch predict.

### ISSUE THREAD

**Issue by thienbui** [pbcquoc/vietocr#107]
Mình có 1 list (100 ảnh). 
Chạy với batch thì 1 số ảnh kết quả bị lệch so với chạy từng ảnh. 

Quốc có thể ngó qua xem có vấn đề gì với batch_predict ko nhé. 

Cảm ơn.

**Comment by pbcquoc** [comment]
Hi @thienbui th
tại vì để chạy batch cần phải padding,  còn chạy từng ảnh thì ko cần, nên dẫn đến kết quả bị sai khác
