### ISSUE TITLE
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

### ISSUE THREAD

**Issue by duonglegiang** [pbcquoc/vietocr#11]
Hi anh, em đang train model của anh theo code trong file vietocr_gettingstart.ipynb thì gặp lỗi sau:
![image](https://user-images.githubusercontent.com/44205911/95188093-2dff7e00-07f6-11eb-89a3-1286c8a9a9a6.png)
Dòng code em chạy là:
trainer = Trainer(config, pretrained=True)

**Comment by giangpb** [comment]
Bạn có chỉnh chỗ nào lúc chạy để train không thế?

**Comment by pbcquoc** [comment]
Hi e, 
Kiểm tra lại tập dataset của e có tạo thành công không nhé.

**Comment by monotuko** [comment]
@pbcquoc anh cho em hỏi em chỉnh vậy đúng chưa ạ
![image](https://user-images.githubusercontent.com/72443171/95210450-b6414b80-0815-11eb-954c-6dc8b8024894.png)
với khúc này mình để nguyên vậy hay chỉnh lại đường dẫn gì không anh?
![image](https://user-images.githubusercontent.com/72443171/95210523-c9ecb200-0815-11eb-85dc-8e7c1265d602.png)
Em cảm ơn.

**Comment by pbcquoc** [comment]
vậy là dc rồi e nhé.

**Comment by pbcquoc** [comment]
@monotuko e bị vấn đề gì thì tạo issue khác xem, trong notebook a có hướng dẫn rồi mà nhỉ

**Comment by duonglegiang** [comment]
@pbcquoc Em cảm ơn anh

**Comment by duonglegiang** [comment]
Em tạo thành công train_hw và valid_hw rồi và chạy tiếp thì bị lỗi như này.
![image](https://user-images.githubusercontent.com/44205911/95309809-d0326b00-08b5-11eb-88a0-ac6b08a6c82b.png)
Dòng code em chạy là: trainer.train()
@pbcquoc Anh xem lại giúp em với ạ

**Comment by pbcquoc** [comment]
các kí tự mà model hình dự đoán được cần được nằm trong list 
vocab: 'aAàÀảẢãÃáÁạẠăĂằẰẳẲẵẴắẮặẶâÂầẦẩẨẫẪấẤậẬbBcCdDđĐeEèÈẻẺẽẼéÉẹẸêÊềỀểỂễỄếẾệỆfFgGhHiIìÌỉỈĩĨíÍịỊjJkKlLmMnNoOòÒỏỎõÕóÓọỌôÔồỒổỔỗỖốỐộỘơƠờỜởỞỡỠớỚợỢpPqQrRsStTuUùÙủỦũŨúÚụỤưƯừỪửỬữỮứỨựỰvVwWxXyYỳỲỷỶỹỸýÝỵỴzZ0123456789!"#$%&''()*+,-./:;<=>?@[\]^_`{|}~ '
e có thể thêm kí tự bằng cách config['vocab']='xyz'

Tuy nhiên, tập vocab này đã full cho tiếng việt rồi, các kí tự khác thường là do lỗi đánh máy, e nên kiểm tra lại dữ liệu và remove hết các mẫu đó nếu ít.

**Comment by duonglegiang** [comment]
@pbcquoc  Vâng, để em kiểm tra lại. Em cảm ơn anh

**Comment by monotuko** [comment]
@duonglegiang bạn ơi cho mình hỏi data train của bạn khoảng bao nhiêu hình vậy?

**Comment by duonglegiang** [comment]
@pbcquoc Hi anh
Em có test model với pre-train model mà anh mới cập nhật trên một số ảnh thì kết quả có tốt hơn, nhưng mà lại bị thừa từ (thừa từ có nghĩa đứng đầu hoặc đứng cuối câu chứ không phải thừa kí tự ạ ). Vậy anh cho em hỏi, chuyện này là vì lí do gì ạ? Theo em nghĩ thì có phải là do cơ chế self-attention của transformer không hay là do data train ạ 
Em cảm ơn anh!
Dưới đây là ví dụ, nhãn đúng của bức ảnh là: Vĩnh Phú Tây, Phước Long, Bạc Liêu ạ
![image](https://user-images.githubusercontent.com/44205911/96268698-8d7a3c80-0ff3-11eb-9c08-419a8d57b3e5.png)

**Comment by duonglegiang** [comment]
@monotuko hiện tại thì mình có khoảng gần 1 triệu ảnh

**Comment by pbcquoc** [comment]
> @pbcquoc Hi anh
> Em có test model với pre-train model mà anh mới cập nhật trên một số ảnh thì kết quả có tốt hơn, nhưng mà lại bị thừa từ (thừa từ có nghĩa đứng đầu hoặc đứng cuối câu chứ không phải thừa kí tự ạ ). Vậy anh cho em hỏi, chuyện này là vì lí do gì ạ? Theo em nghĩ thì có phải là do cơ chế self-attention của transformer không hay là do data train ạ
> Em cảm ơn anh!
> Dưới đây là ví dụ, nhãn đúng của bức ảnh là: Vĩnh Phú Tây, Phước Long, Bạc Liêu ạ
> ![image](https://user-images.githubusercontent.com/44205911/96268698-8d7a3c80-0ff3-11eb-9c08-419a8d57b3e5.png)
Hi e, 
Nhãn đúng của bức ảnh phải là "Vĩnh Phú Tây, Phước Long Bạc Liêu Điện" chứ nhỉ ?

**Comment by duonglegiang** [comment]
@pbcquoc cái bức ảnh dưới là cái nhãn nó in ra em chụp màn hình lại thôi ạ, đây mới là ảnh gốc ạ
![image](https://user-images.githubusercontent.com/44205911/96271643-54dc6200-0ff7-11eb-854f-c01ef8affaaa.png)

**Comment by pbcquoc** [comment]
Hi e, a cũng biết vấn đề này trước rồi, a nghĩ có lẽ là do thông tin tại biên ảnh bị mất do mô hình CNN cần padding để đảm bảo kích thước không đổi. 
Tuy nhiên, hiện tại a vẫn chưa thử cách a vừa nói. em có thể đọc code và train lại theo cách trên xem sao

**Comment by pbcquoc** [comment]
data e có bao nhiêu ảnh, e train bao nhiêu step, acc full seq bao nhiêu nhỉ ?

**Comment by duonglegiang** [comment]
@pbcquoc Vâng, em sẽ xem lại ạ, data em có gần 1tr ảnh, acc full seq: 85%

**Comment by duonglegiang** [comment]
@pbcquoc Hi anh
Anh cho em hỏi với tập data 10m thì anh train với bao nhiêu step để có pretrain model đó ạ? 
Em cảm ơn anh!
