### ISSUE TITLE
Lỗi khi training custom dataset

### ISSUE THREAD

**Issue by bipowerhcmcity** [pbcquoc/vietocr#110]
Chào bạn @pbcquoc , mình dùng repo được cập nhật đến ngày hôm nay (21/10/2023). Mình chạy Colab thì nó bị dừng ở lỗi này: 
![image](https://github.com/pbcquoc/vietocr/assets/50283329/8ce76268-65ca-4f69-8cbe-815a4a3610bc)

Hi vọng được bạn giúp đỡ

**Comment by pbcquoc** [comment]
pip install vietocr=0.3.12 là được nhé @bipowerhcmcity
