### ISSUE TITLE
Lỗi không chạy được sau khi cài

### ISSUE THREAD

**Issue by vnpresent88** [pbcquoc/vietocr#111]
Mình có install bản vietocr 0.3.12 trên pypip,nhưng khi chạy test thì gặp lỗi này ạ
![image](https://github.com/pbcquoc/vietocr/assets/137747187/afab05f7-1574-4559-adee-594bba98770b)
![image](https://github.com/pbcquoc/vietocr/assets/137747187/be4fe0dc-05ee-46aa-b3c3-5fae711b62c5)

mình cảm ơn!

**Comment by pbcquoc** [comment]
torch của @vnpresent88 không có cuda nên bạn để device='cpu' nhé.

**Comment by longtran84** [comment]
@pbcquoc HI anh em gặp lỗi sau khi import code va run a :
![Screenshot from 2024-01-04 11-20-37](https://github.com/pbcquoc/vietocr/assets/33080326/08464d15-da9d-4e87-aafb-15522e8d9e7d)

**Comment by David-Hoa2023** [comment]
Tôi gặp lỗi tương tự mong bạn giúp.
--> 149 img = img.resize((new_w, image_height), Image.ANTIALIAS)
    151 img = np.asarray(img).transpose(2,0, 1)
    152 img = img/255

AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'

**Comment by pbcquoc** [comment]
HI @David-Hoa2023 
để fix nhanh thì dùng lệnh này nhé 
```pip install Pillow==9.5.0```
