### ISSUE TITLE
Remove n invalid images

### ISSUE THREAD

**Issue by phamnguyet2003** [pbcquoc/vietocr#115]
![image](https://github.com/pbcquoc/vietocr/assets/146205960/632f31c2-fc68-4d4b-99c0-c09faefc8959)
Cho em hỏi là bộ dataset có điều kiện gì cần lưu ý khum ạ??? Em làm theo cái nguyên mẫu này vẫn bị bảo invalid images
.
├── img
│   ├── 00000.jpg
│   ├── 00001.jpg
├── train_annotation.txt # nhãn tập train 
└── val_annotation.txt # nhãn tập test

**Comment by pbcquoc** [comment]
Hi @phamnguyet2003 

Upload sample data lên mình coi nhé

**Comment by phamnguyet2003** [comment]
@pbcquoc oh sample data của em hôm qua có chút vấn đề hôm nay sửa được chạy được rồi. Em cảm ơn anh nhé!!!
