### ISSUE TITLE
New PIL not AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'

### ISSUE THREAD

**Issue by tanpham380** [pbcquoc/vietocr#116]
![image](https://github.com/pbcquoc/vietocr/assets/74082201/3945a487-0e31-4eb7-802c-fa4fd22214eb)

**Comment by PhamMinhTien05102001** [comment]
same issue~

**Comment by tanpham380** [comment]
> same issue~

:D downgrade PIL là được nhưng mà nhiều cái thư viện nó cũng update lên bản mới yều cầu xài PIL 10 thì nó sẽ xung đột với VietOCR này

**Comment by pbcquoc** [comment]
cho mình sửa lại code cho mọi người tiện sử dụng

**Comment by tanpham380** [comment]
> cho mình sửa lại code cho mọi người tiện sử dụng
hiện tại mình có một cái App sử dụng PIL 10. thì chuyển cái pil.ANTIALIAS => LANCZOS .... còn nếu không bắt buộc xài pil 10 thì downgrade pil 10. => 9.5.0
from pkg_resources import parse_version
from PIL import Image as pil
 if parse_version(pil.__version__)>=parse_version('10.0.0'):
        pil.ANTIALIAS=pil.LANCZOS

**Comment by tanpham380** [comment]
![image](https://github.com/pbcquoc/vietocr/assets/74082201/5becfc80-ffd2-4e64-81c7-99bfbb56a2b7)
mình thấy có 1 bạn pull cái này rồi, bác check thử @pbcquoc

**Comment by pbcquoc** [comment]
Fixed
