### ISSUE TITLE
Load dataset

### ISSUE THREAD

**Issue by minhduc01168** [pbcquoc/vietocr#117]
Em gặp lỗi sau khi thực hiện fine-tuning với bộ dataset: train: 3200 mẫu, test: 514 mẫu
![Screenshot from 2024-02-04 01-09-20](https://github.com/pbcquoc/vietocr/assets/81012512/ffc97541-9047-4f4b-8ed5-0c81c31977b1)
![Screenshot from 2024-02-04 01-09-30](https://github.com/pbcquoc/vietocr/assets/81012512/5ea2e638-29b8-4c41-9551-7b9466f3e289)
Cấu trúc dataset em để như sau:
![Screenshot from 2024-02-04 11-32-24](https://github.com/pbcquoc/vietocr/assets/81012512/5cd62424-c6b7-4ed2-ad55-40c3ee5dc42f)
![Screenshot from 2024-02-04 11-32-31](https://github.com/pbcquoc/vietocr/assets/81012512/ea1e125d-a4cf-4fc5-9a01-fbecfb64cf31)
Em chưa hiểu sai ở đâu, mong anh có thể giúp em sửa lỗi ạ. Em xin cảm ơn ạ

**Comment by pbcquoc** [comment]
Hi em, 
path với label cách nhau bằng \t nhé.

**Comment by minhduc01168** [comment]
Em để cách nhau bằng 1 tab rồi ạ

**Comment by pbcquoc** [comment]
e check bằng code hay bằng tay vậy ?

**Comment by pbcquoc** [comment]
với remove \t trong label đi nữa e nha

**Comment by minhduc01168** [comment]
Em check bằng tay ạ, xóa \t ở đâu ạ anh

**Comment by pbcquoc** [comment]
File train/test của e, có 2 cột, một cột tên file, một cột nhãn, e remove \t trong nhãn ra nha.
