### ISSUE TITLE
Augmentation Issues

### ISSUE THREAD

**Issue by phamnguyet2003** [pbcquoc/vietocr#118]
Khi em visualize dataset, em thấy có mấy trường hợp như này:
![image](https://github.com/pbcquoc/vietocr/assets/146205960/3a98fa54-ce11-4af5-83fe-51a88ea72431)
![image](https://github.com/pbcquoc/vietocr/assets/146205960/5b310679-89b1-4cf6-b0c5-9e9efe923af1)
![image](https://github.com/pbcquoc/vietocr/assets/146205960/3a8ae6c0-d96f-40fc-a70f-343e5c2a96e6)
Em nghĩ nó sẽ ảnh hưởng đến kết quả parameter thu được. Làm sao để em có thể chủ động trong việc augment dataset ạ?

**Comment by pbcquoc** [comment]
em check file config và disable cái masked_language_model nha 
aug:
    image_aug: true
    masked_language_model: true
