### ISSUE TITLE
Thắc mắc về đầu vào Image, Acc per char

### ISSUE THREAD

**Issue by KaiKenju** [pbcquoc/vietocr#121]
Chào a, cảm ơn a vì đã đóng góp sản phẩm này cho cộng đồng,
Hiện tại e đang có thắc mắc là:
- có có thử pretrained lại model của a(run lại ) trong vietocr_gettingstart và ở phần trainer, thì e có chạy 20000iter trong 2h trên colab và acc per char của e khá thấp chỉ đạt 0.63 thì e nên cải thiện điều gì ?

![image](https://github.com/pbcquoc/vietocr/assets/94727276/5315cf88-c036-4279-8ef3-4646d0e453cf)

- ngoài ra e vẫn chưa hiểu về cái input: có phải ảnh đầu image đc token hóa thành các vector đặc trưng (word embedding) hay là image đc phân đoạn ra rồi làm phẳng ...
![image](https://github.com/pbcquoc/vietocr/assets/94727276/bb859981-d344-4e67-b900-626b3880c082)
(e vẫn chưa hiểu cốt lõi nó lắm)
A có thể giải đáp giúp e với, E cảm ơn. Hi vọng đc a phản hồi sớm.

**Comment by pbcquoc** [comment]
https://pbcquoc.github.io/vietnamese-ocr/
Em tham khảo tài liệu này nhé.
