### ISSUE TITLE
Can not create dataset on Jupyter Notebook because of [tab] definition

### ISSUE THREAD

**Issue by Gken92k10820** [pbcquoc/vietocr#124]
Jupyter Notebook doesn't directly support using the tab character (\t) for splitting due to its prioritization of code completion and indentation. So, when I ran the code 'trainer = Trainer(config, pretrained=True)', all dataset would be invalid and deleted. Then, I tried to replace '\t' with 4 spaces (as like as tab space) and got this error 'ValueError: not enough values to unpack (expected 2, got 1)'. The question is "How can I define tab character in .txt files as 'train_annotation_line' and 'test_annotation_line' on Jupyter Notebook to create dataset?". Thank you!

**Comment by Gken92k10820** [comment]
fixed

**Comment by hhiep1504** [comment]
can you share how to fix this?

**Comment by Gken92k10820** [comment]
> can you share how to fix this?

it is not because of tab definition, the path to your data should not include ./ at the first of line
