### ISSUE TITLE
StopIteration:   During handling of the above exception, another exception occurred:

### ISSUE THREAD

**Issue by Vinhbuster** [pbcquoc/vietocr#13]
Dạ chào anh, em có thử train code của anh với dataset nhỏ ( chỉ gồm 4 ảnh) để thử nghiệm , quá trình tạo dataset thành công nhưng khi visualize lại không hiện ra gì và train thì hiện lỗi như hình ạ, không biết có phải chỉnh lại tham số valid hay iter gì cho phù hợp với số lượng ảnh trong dataset không ạ. Em cảm ơn

**Comment by Vinhbuster** [comment]
![xyz](https://user-images.githubusercontent.com/48577648/95232725-1690b700-082f-11eb-8442-a1f5b00c20e5.png)

**Comment by Vinhbuster** [comment]
![abc](https://user-images.githubusercontent.com/48577648/95232963-450e9200-082f-11eb-9f8c-49f45bb69d4d.png)

**Comment by Vinhbuster** [comment]
![xyz](https://user-images.githubusercontent.com/48577648/95233171-50fa5400-082f-11eb-8d68-3bb9dbe39ef2.png)

**Comment by pbcquoc** [comment]
do e có 4 ảnh mà batch_size thì chắc là 32 nên nó ko train được nhé, ví mỗi lần a sẽ đọc đúng batch_size của những ảnh có kích thước gần giống nhau, 
e thử giảm batch_size xuống còn 1 hoặc tốt nhất là tăng số ảnh train lên nhé.

**Comment by Vinhbuster** [comment]
Dạ cảm ơn anh ạ

**Comment by monotuko** [comment]
@Vinhbuster bạn debug được lỗi này chưa mình cũng bị vậy mà data mình khoảng 10k ảnh.

**Comment by monotuko** [comment]
@pbcquoc data của em tầm 10k ảnh những cũng bị lỗi này ạ? Anh có cách nào chỉnh không ạ?
Em cảm ơn anh.

**Comment by pbcquoc** [comment]
@monotuko a nghĩ là dataset e tạo chưa thành công, 
![image](https://user-images.githubusercontent.com/19279523/95656064-e3ec0480-0b35-11eb-8850-330828cec9a3.png)
e chú ý là lúc tạo dataset có ghi ra dòng, created dataset with xxx samples chưa. 
thử dùng lệnh trainer.visualize_dataset()
để xem thử có hiển thị các mẫu trong dataset vừa được tạo ra không e nhé.

**Comment by monotuko** [comment]
@pbcquoc anh cho em hỏi là file train_anotation.txt với validation.txt ví dụ cú pháp từng dòng trong đó là name_folder/name_image + '\t' + chữ của hình đúng không ạ? 
Em cảm ơn anh.

**Comment by pbcquoc** [comment]
@monotuko tên file và text ngăn cách bởi \tab, do đó nếu có tab trong bất kì vị trí nào trên 1 dòng cũng đọc ko được e nhé.
