### ISSUE TITLE
Predicted acurracy is 0, some keys of config file was wrong.  

### ISSUE THREAD

**Issue by ducthangqd1998** [pbcquoc/vietocr#14]
Em chào anh, em có chạy file notebook. Thì em có gặp một số lỗi như sau: 
![image](https://user-images.githubusercontent.com/33730129/95289220-6ce41100-0894-11eb-89c0-9aef624e45f6.png)
Em có thực hiện bằng cách thay đổi thành các key khác: 
```
config["optimizer"]["max_lr"] = 0.1
config["optimizer"]["total_steps"] = 4000

del config["optimizer"]["init_lr"]
del config["optimizer"]["n_warmup_steps"]
```
Ngoài ra thì em còn thấy missmatching shape model.
Khi tiến hành chạy thì kết quả dự đoán là 0%. Điều này có phải là do chưa train đủ lâu hay không ạ. 
![image](https://user-images.githubusercontent.com/33730129/95289500-09a6ae80-0895-11eb-9cf1-dc9adccd7a45.png)
Em xin cảm ơn!

**Comment by pbcquoc** [comment]
hiện tại e sài version này nhé 
pip install vietocr==0.1.9

**Comment by monotuko** [comment]
@ducthangqd1998  bạn ơi cho mình hỏi data train bạn tầm bao nhiêu hình vậy?

**Comment by ducthangqd1998** [comment]
> hiện tại e sài version này nhé
> pip install vietocr==0.1.9
Với version thì em bị lỗi missmatching. Mà em đã fix được rồi, do em để lr quá cao thì phải. E cảm ơn anh.

**Comment by ducthangqd1998** [comment]
@monotuko Mình sử dụng với bộ dữ liệu này của anh luôn [link](https://drive.google.com/drive/folders/1Qa2YA6w6V5MaNV-qxqhsHHoYFRK5JB39)
