### ISSUE TITLE
KeyError: Caught KeyError in DataLoader worker process 1.

### ISSUE THREAD

**Issue by tonhathuy** [pbcquoc/vietocr#15]
Chào anh, em train lại model của anh trên dataset [SROIE](https://rrc.cvc.uab.es/?ch=13&com=downloads), em đã config lại dataset cho giống dataset của anh mà khi train nó bị lỗi này em fix hoài không được , 
![image](https://user-images.githubusercontent.com/45118883/95554942-3e546a80-0a3b-11eb-8153-b1b1e033176f.png)
Code và dataset của em trên [colab](https://drive.google.com/file/d/1XfOBGG7mRnr8HEwQOCk6fllRVJEKU-fY/view?usp=sharing)
em cảm ơn

**Comment by pbcquoc** [comment]
Hi e, 
hiện tại a dự đoán các kí tự nằm trong vocab: 'aAàÀảẢãÃáÁạẠăĂằẰẳẲẵẴắẮặẶâÂầẦẩẨẫẪấẤậẬbBcCdDđĐeEèÈẻẺẽẼéÉẹẸêÊềỀểỂễỄếẾệỆfFgGhHiIìÌỉỈĩĨíÍịỊjJkKlLmMnNoOòÒỏỎõÕóÓọỌôÔồỒổỔỗỖốỐộỘơƠờỜởỞỡỠớỚợỢpPqQrRsStTuUùÙủỦũŨúÚụỤưƯừỪửỬữỮứỨựỰvVwWxXyYỳỲỷỶỹỸýÝỵỴzZ0123456789!"#$%&''()*+,-./:;<=>?@[\]^_`{|}~ '

Do đó, e cần bổ sung kí tự kia vào tập vocab bằng cách thay đổi biến config['vocab']
![image](https://user-images.githubusercontent.com/19279523/95559455-fc7af280-0a41-11eb-83ee-4503399c3c7d.png)

**Comment by tonhathuy** [comment]
dạ lúc đầu nó văn ra lỗi này,  KeyError: '·' , em thử thêm '·' vào vocab thì nó chuyển qua KeyError: " ' " như trên
Nhưng giờ em reset chạy lại colab thì có thêm '·'  cũng ko fix dc lỗi KeyError: '·'
config['vocab'] = 'aAàÀảẢãÃáÁạẠăĂằẰẳẲẵẴắẮặẶâÂầẦẩẨẫẪấẤậẬbBcCdDđĐeEèÈẻẺẽẼéÉẹẸêÊềỀểỂễỄếẾệỆfFgGhHiIìÌỉỈĩĨíÍịỊjJkKlLmMnNoOòÒỏỎõÕóÓọỌôÔồỒổỔỗỖốỐộỘơƠờỜởỞỡỠớỚợỢpPqQrRsStTuUùÙủỦũŨúÚụỤưƯừỪửỬữỮứỨựỰvVwWxXyYỳỲỷỶỹỸýÝỵỴzZ0123456789!"#$%&''()*+,-./:;<=>?@[\]^_`{|}~· '

**Comment by pbcquoc** [comment]
em thống kê các kí tự trong dataset kia và thay toàn bộ vào config['vocab'] nhé

**Comment by tonhathuy** [comment]
Em mới fix được rồi anh, e search '·'  trong dataset rồi xóa nó đi :)) 
do ký tự này chỉ có 1 chổ trong dataset nên ko ảnh hưởng 
em cảm ơn anh
