### ISSUE TITLE
Missing_key khi predict bằng attention_seq2seq

### ISSUE THREAD

**Issue by monotuko** [pbcquoc/vietocr#16]
Em chào anh, em predict thử bằng attention seq2seq nhưng bị lỗi này, em nghĩ do file weight của anh là do train với transformer nên bị lỗi như vậy. Nếu em muốn dùng attention seq2seq thì phải chỉnh như thế nào ạ? 
Mong anh chỉ giúp, em cảm ơn ạ.
![image](https://user-images.githubusercontent.com/72443171/95937505-234e7580-0e02-11eb-8a3f-87ef544525fb.png)
![image](https://user-images.githubusercontent.com/72443171/95937485-1a5da400-0e02-11eb-9318-39c1889ec51b.png)

**Comment by pbcquoc** [comment]
Hi e, hiện tại e cần cập nhật lên version 0.3.2 và pretrained model hiện tại chỉ có cho vgg-transformer, còn vgg-seq2seq a sẽ cập nhật trong tuần tiếp theo nhé.

**Comment by monotuko** [comment]
dạ em cảm ơn anh ạ.
