### ISSUE TITLE
Lõi khi chạy demo 

### ISSUE THREAD

**Issue by 1653134** [pbcquoc/vietocr#17]
![image](https://user-images.githubusercontent.com/46516057/95947964-dd9da700-0e19-11eb-966d-4b83c932e33a.png)
Em làm theo file hướng dẫn thì gặp lỗi ở 2 phiên bản khác nhau. Em xin cách khắc phục ạ!

**Comment by monotuko** [comment]
tui cũng mới chạy version 0.3.2 thì bị lỗi này xong quay về 0.1.9 chạy lại thì chạy không được luôn

**Comment by pbcquoc** [comment]
Hi e, 
e mới thay đổi lại hướng dẫn trên notebook e xem lại nhé
https://github.com/pbcquoc/vietocr/blob/master/vietocr_gettingstart.ipynb

**Comment by pbcquoc** [comment]
@monotuko kết bạn vói a qua fb này nhé
https://www.facebook.com/pbcquoc

**Comment by 1653134** [comment]
file weight của em nó lưu trong cache bị lỗi xem xóa down lại thì được! Cảm ơn anh
