### ISSUE TITLE
lỗi khi sử dụng file predict

### ISSUE THREAD

**Issue by ducbluee** [pbcquoc/vietocr#2]
sau khi em clone có build và instal. nhưng khi predict thì lại xảy ra lỗi, anh có thể giúp em được không ạ

**Comment by xxxpsyduck** [comment]
@ducbluee em phải miêu tả lỗi chi tiết hơn thì người khác mới giúp được chứ

**Comment by ducbluee** [comment]
> @ducbluee em phải miêu tả lỗi chi tiết hơn thì người khác mới giúp được chứ

sau khi em pretrain, em đã có 1 file transformerocr_checkpoint.pth em đã sử dụng files đó để predict nhưng xảy ra lỗi dù em đã thay đổi trong config. Anh có thể giúp em được ko aj!!
![Screenshot from 2020-06-09 08-36-19](https://user-images.githubusercontent.com/48615021/84096555-6a7bc280-aa2c-11ea-9df2-9ea67ba97e51.png)

**Comment by xxxpsyduck** [comment]
@ducbluee em phải sửa lại các đường dẫn trong `config/vgg-transformer.yml`

**Comment by ducbluee** [comment]
> @ducbluee em phải sửa lại các đường dẫn trong `config/vgg-transformer.yml`

em đã sửa các đường dẫn sang file của mình thì lại xảy ra lỗi như sau ạ
![Screenshot from 2020-06-09 14-16-58](https://user-images.githubusercontent.com/48615021/84117702-1ee10d00-aa5c-11ea-892a-2e2e27aa8110.png)

**Comment by xxxpsyduck** [comment]
@ducbluee máy em có gpu không và đã cài cuda chưa?

**Comment by ducbluee** [comment]
> @ducbluee máy em có gpu không và đã cài cuda chưa?

em set device là cpu vẫn cần gpu ạ

**Comment by ducbluee** [comment]
@xxxpsyduck em cảm ơn anh, em sửa được rồi ạ

**Comment by xxxpsyduck** [comment]
@ducbluee nếu giải quyết được rồi thì close issue đi em nhé
