### ISSUE TITLE
Về pretrain model

### ISSUE THREAD

**Issue by duonglegiang** [pbcquoc/vietocr#21]
@pbcquoc Em chào anh,
Anh cho em hỏi với tập data 10m của anh thì anh train với bao nhiêu step để có pretrain model đó ạ?
Em cảm ơn anh!

**Comment by pbcquoc** [comment]
1m steps nhé e

**Comment by duonglegiang** [comment]
Vâng, em cảm ơn anh!

**Comment by FahNos** [comment]
chào anh, anh có thể chia sẻ đường link tải bộ dữ liệu 10m ảnh này được không @pbcquoc
