### ISSUE TITLE
Bounding box khác nhau cho kết quả khác nhau

### ISSUE THREAD

**Issue by titikid** [pbcquoc/vietocr#22]
Hi a Quốc, em đang test thử model với 1 số loại chữ khác nhau thì gặp vấn đề khi thay đổi vùng crop. Ví dụ như sau:

![vietnam1_3](https://user-images.githubusercontent.com/17918935/100047050-1df23b00-2e44-11eb-8478-be605bca6ef2.jpg)
Kết quả vgg19_bn-seq2seq: **UASORU7250KXXY**

![vietnam1_4](https://user-images.githubusercontent.com/17918935/100047113-3d896380-2e44-11eb-927b-95e592419ffa.jpg)
Kết quả vgg19_bn-seq2seq: **UASCRU7250KXY**

![vietnam_1_crop2](https://user-images.githubusercontent.com/17918935/100047132-5265f700-2e44-11eb-8ae7-a25da565856d.jpg)
Kết quả vgg19_bn-seq2seq: **UASORU7250KXY**

Khi e test bằng model transformer thì cũng bị vấn đề tương tự. Vậy có cách nào để giải quyết vấn đề này hoặc có gợi ý nào về việc crop đẹp để model đọc tốt ko anh?

**Comment by pbcquoc** [comment]
Hi e, 
vấn đề này a đã nắm được, hiện tại a đang tìm cách aug data trước, và bổ sung dữ liệu. 
Tuy nhiên, nếu e muốn dùng cho các dự án thực tế thì cần train lại trên tập dataset riêng nhé, pretrained model chỉ cung cấp kết quả tạm ổn để thử nghiệm thôi.

**Comment by titikid** [comment]
Vâng, em cảm ơn anh nhé
