### ISSUE TITLE
OCR CMND

### ISSUE THREAD

**Issue by nShieldSolo** [pbcquoc/vietocr#23]
Xin chào anh Quốc,
    Cám ơn anh đã tạo ra thư viện OCR cho người việt. Em có 3 vần đề muốn hỏi anh là:
     + Em muốn lấy thông tin từ CMND thông qua Transformer thì em có thể scan 1 lần toàn bộ CMND không ạ hay phải cắt nhỏ ra từng box?
     + Nếu train CMND thì em phải train tầm bao nhiêu anh thì có thể sử dụng ạ?
     + Do em làm .NET nên em có thử download file weights như hình thì thấy kết quả ra không đúng, không biết em có làm sai bước nào không? :D 
![image](https://user-images.githubusercontent.com/58923848/102322360-864ebb00-3fb1-11eb-9cbe-dcdbfd5f5188.png)
* input
![aa1](https://user-images.githubusercontent.com/58923848/102322730-1ab91d80-3fb2-11eb-972d-57e5e7745ef5.jpg)
* Result
![image](https://user-images.githubusercontent.com/58923848/102322550-d0d03780-3fb1-11eb-9e85-2c1e0b6d9c67.png)
=> Kết quả không như mong muốn ạ. Anh có thể chỉ em cách để tăng độ chính xác?

Chúc anh nhiều sức khỏe.

**Comment by buiquangmanhhp1999** [comment]
Bạn có thể tham khảo bài viết này của mình nhé https://viblo.asia/p/trich-xuat-thong-tin-tu-chung-minh-thu-bJzKmaRwK9N

**Comment by nShieldSolo** [comment]
> Bạn có thể tham khảo bài viết này của mình nhé https://viblo.asia/p/trich-xuat-thong-tin-tu-chung-minh-thu-bJzKmaRwK9N

Cám ơn bạn nhiều nha. :D
