### ISSUE TITLE
Train với ảnh gray

### ISSUE THREAD

**Issue by chuan298** [pbcquoc/vietocr#25]
Em chào anh ạ, anh cho em hỏi là em cần config như thế nào để có thể train với ảnh gray ạ, em có thử convert('L') trong hàm process_image() ở file translate.py nhưng em đang gặp lỗi ở phần augmentor ảnh ạ

**Comment by pbcquoc** [comment]
Hi e, 
Hiện tại mô hình được huấn luyện khi có đủ 3 kênh màu, nếu e muốn ảnh gray thì sau khi convert sang ảnh gray thì thêm các kênh còn lại vào cho đủ 3 kênh nhé.
