### ISSUE TITLE
Train mới bị lỗi

### ISSUE THREAD

**Issue by wdrqef** [pbcquoc/vietocr#26]
Em cần train tiếp với bộ data anh cung cấp. Nhưng lúc train bị lỗi như vầy
Em để nguyên các folder vi_00,vi_01,.. và tạo mới file train_annotation.txt và test annotation.txt nên các file này sẽ như v: vi_00  abc
vi_01 aksk
....
Em không biết nên sửa sao
![image](https://user-images.githubusercontent.com/71751475/103139862-6044bb80-4713-11eb-807c-e56c9180760b.png)

**Comment by pbcquoc** [comment]
Hi e, 
cho a xem full lỗi thử. 
file annotation thì tên ảnh với label cách nhau bằng tab e nhé.

**Comment by wdrqef** [comment]
![image](https://user-images.githubusercontent.com/71751475/103145512-b135cd80-476e-11eb-9f10-87f7b0d9e37e.png)
Dạ đây a. Em chỉ dụng được data trong file Inkdataline
Em có tab và sử dụng nhưng bị lỗi khi train những ảnh trong folder vi_00, vi_01.... thì bị như v ạ

**Comment by pbcquoc** [comment]
Hi e,
kí tự nó báo không có trong tập từ điển nên nó thường là kí tự lạ, e nên remove nó ra trước nhé. 
các kí tự phổ biến của tiếng việt a đã thêm đủ rồi. e có thể lấy tại config['vocab'] nhé

**Comment by wdrqef** [comment]
Dạ cảm ơn a.
Em đã sửa và chạy được rồi ạ.
Mà a cho e hỏi thêm 1 câu: là cái data khoảng 1m ảnh tự phát sinh là do cơ chế nào nó phát sinh ra vậy a. Em cảm ơn a

**Comment by pbcquoc** [comment]
A phát sinh dựa vào thư viện này. https://github.com/Belval/TextRecognitionDataGenerator
Tuy nhiên đó chỉ là một phần dữ liệu mà a dùng để train mô hình đang cung cấp e nhé.
