### ISSUE TITLE
File pretrain cho backbone seq2seq.

### ISSUE THREAD

**Issue by dangvitin** [pbcquoc/vietocr#27]
Anh có thể chia sẻ file pretrain của seq2seq không ạ, em chỉ tìm được pretrain của transformer thôi ạ. Cảm ơn anh.

**Comment by pbcquoc** [comment]
Hi e,
Khi e set config là vgg_seq2seq thì model sẽ tự download file pretraine model về, 
nên e ko cần download thủ công về nhé.

**Comment by dangvitin** [comment]
Vâng, cảm ơn anh, em làm được rồi.
