### ISSUE TITLE
model attention OCR

### ISSUE THREAD

**Issue by syanhcva** [pbcquoc/vietocr#28]
bạn ơi mình ko thấy trong code cũng như public model attention OCR mà chỉ thấy transformer OCR, bạn có thể cho mình link download được không.
Cám ơn tác giả

**Comment by pbcquoc** [comment]
Hi bạn, 
đổi bạn đổi confign từ ```vgg_transformer``` thành ```vgg_seq2seq``` và set pretrained=True thì model tự download về nhé. xem file notebook mình có hướng dẫn rồi đấy.

**Comment by syanhcva** [comment]
thanks bạn, mình đã thử đc rồi

**Comment by cuongngm** [comment]
cho em hỏi là cache, id_or_url và md5 trong config sửa như nào để train vgg_seq2seq đc ạ. Em đổi tên không thì chưa train đc vì nó cứ tải cái weights của transformerocr

**Comment by pbcquoc** [comment]
Hi em, 
Như này có nghĩa là em ko có quyền ghi vào thư mục /tmp 
Em có thể đổi config['pretrain']['cached']= 'tranformerorc.pth'
để ghi trực tiếp vào thư mục hiện tại luôn nhé.

**Comment by cuongngm** [comment]
em cảm ơn ạ
