### ISSUE TITLE
vv sử dụng ảnh to

### ISSUE THREAD

**Issue by chuyendq9x** [pbcquoc/vietocr#29]
Dear a Quốc,

Hiên tại e thấy VietOCR đang đọc được ảnh bé. giờ e muốn đọc ảnh với kích thước A3 thì làm thế nào ạ

**Comment by pbcquoc** [comment]
Hi em, 
vietocr chỉ đọc theo từng dòng, để đọc ảnh có nhiều dòng em cần tách văn bản đó ra thành nhiều dòng rồi mới đọc bằng vietocr nhé. 
Để xác định từng dòng em có thể sài mô hình ctpn text detection.
