### ISSUE TITLE
Lỗi khi chạy demo

### ISSUE THREAD

**Issue by chuyendq9x** [pbcquoc/vietocr#30]
Dear anh,

Em có làm như hướng dẫn tạo file chạy demo : https://github.com/pbcquoc/vietocr/blob/master/vietocr_gettingstart.ipynb
Khi chạy e bị lỗi này. do máy e k có kết nối mạng
![image](https://user-images.githubusercontent.com/21030546/104292533-8ded7b00-54ef-11eb-80f1-dd4e11ca5cdd.png)

e đọc code thấy đoạn này kết nối đến github. e chuyển cái này thành file offline được k ạ.

![image](https://user-images.githubusercontent.com/21030546/104292635-a5c4ff00-54ef-11eb-86da-d3ad939d2d2f.png)

**Comment by pbcquoc** [comment]
Hi e, 
Em cần có mạng để download config và model nữa nhé.

**Comment by chuyendq9x** [comment]
Hi anh,

E đã dow về 1 lần rồi ạ. Sau đó e chạy offline được không

**Comment by pbcquoc** [comment]
Để chạy được thì e có thể sửa lại code trong hình e gửi đấy nhé. tải file đó offline về rồi load lên

**Comment by chuyendq9x** [comment]
![image](https://user-images.githubusercontent.com/21030546/104704550-61ce3600-574b-11eb-8926-91491c272725.png)
e viết như ảnh trên. sau đó chạy nó báo lỗi như ảnh dưới. a xem nó bị sao ạ. e chưa code python bao giờ
![image](https://user-images.githubusercontent.com/21030546/104704571-67c41700-574b-11eb-889e-cd69fe0bd233.png)
e viết như ảnh trên. sau đó chạy nó báo lỗi như ảnh dưới
