### ISSUE TITLE
Dùng CPU để chạy thử

### ISSUE THREAD

**Issue by BangNguyenTTF** [pbcquoc/vietocr#31]
Tác giả cho hỏi, máy mình hiện tại ko có GPU, xuất hiện lỗi này 

![Screenshot 2021-01-13 124656](https://user-images.githubusercontent.com/75062710/104425055-c5712b80-55b2-11eb-9a75-baf4fcce6148.png)

Giờ mình phải config tại đâu để có thể chạy thử bằng CPU vậy ạ ? Cảm ơn tác giả

**Comment by pbcquoc** [comment]
Hi bạn, 
Đổi config['device'] = 'cpu' # device chạy 'cuda:0', 'cuda:1', 'cpu'
Bạn tham khảo https://pbcquoc.github.io/vietocr/ nhé.

**Comment by BangNguyenTTF** [comment]
> Hi bạn,
> Đổi config['device'] = 'cpu' # device chạy 'cuda:0', 'cuda:1', 'cpu'
> Bạn tham khảo https://pbcquoc.github.io/vietocr/ nhé.

Thank bác, đã ok ạ
Kết quả test rất tốt tuy nhiên chỉ chạy dc ở những ảnh có 1 dòng text, còn những ảnh có từ 2 dòng text trở lên (xuống dòng) thì không đọc được. Có cách nào không bác nhỉ.

**Comment by pbcquoc** [comment]
Bạn cần tách thành từng dòng trước, 
Cái này gọi là text line detection. Bạn có thể sài thử các thư viện như ctpn hay craft nhé

**Comment by BangNguyenTTF** [comment]
> Bạn cần tách thành từng dòng trước,
> Cái này gọi là text line detection. Bạn có thể sài thử các thư viện như ctpn hay craft nhé

Cảm ơn bác ạ
