### ISSUE TITLE
predict text with batch images

### ISSUE THREAD

**Issue by hiendoan95** [pbcquoc/vietocr#32]
I'm using Tesseract to detect texts and extract text regions. Those images have the different sizes.

How could I use the transformerOCR as the batch predicter for those images?

**Comment by pbcquoc** [comment]
Hi e, 
Hiện tại model chỉ support cho từng ảnh, em có thể gọi nhiều lần để dự đoán cho nhiều ảnh.

**Comment by hiendoan95** [comment]
Hi anh Quốc, 
Theo em thấy trong code của hàm translate dùng để predict text có cho phép detect với batch image.
Em đã thử dùng resize để các ảnh có cùng độ cao và dùng padding để độ dài ảnh bằng nhau.

Tốc độ predict theo batch nhanh hơn predict từng ảnh (predict trên CPU với 20 ảnh nhanh hơn 20s). Tuy nhiên độ chính xác kém hơn (có thể do mô hình em train chưa được tốt).

**Comment by pbcquoc** [comment]
Mô hình a train theo batch nhưng không có padding. 
Nên e thêm padding vào có thể gây ra sai nhiều hơn.
