### ISSUE TITLE
Lỗi khi load model vgg_seq2seq

### ISSUE THREAD

**Issue by LongAiden** [pbcquoc/vietocr#33]
Dear anh,

Khi dùng code của anh em có load thử model vgg_seq2seq thì gặp lỗi này ạ (em đã cập nhật vietocr version mới nhất)

![Capture](https://user-images.githubusercontent.com/54759764/104852579-5dae3e00-592e-11eb-9267-24a80ef82dcf.PNG)

Không biết các tham số của mô hình này em có điền sai ở đâu không ạ vì mô hình vgg_transformer em vẫn dùng được bình thường

**Comment by pbcquoc** [comment]
comment dòng config['weight'] lại e nhé,

**Comment by LongAiden** [comment]
Dạ vâng em cảm ơn ạ
