### ISSUE TITLE
Dùng custom vocab khi test

### ISSUE THREAD

**Issue by ethanthai2** [pbcquoc/vietocr#34]
Chào bạn, mình muốn chỉnh sửa vocab của mình thành chỉ những số từ 0-9 khi prediect thì có thể chỉnh được ở đâu ạ.

Khi mình chỉnh config['vocab'] = '0123456789' khi init_detector thì bị lỗi size mismatch.

**Comment by pbcquoc** [comment]
Bạn chỉnh lại tập vocab thì phải train lại model dựa trên tập dữ liệu mới của bạn thì mới nhận dạng được nhé.

**Comment by ethanthai2** [comment]
Cảm ơn ạ!
