### ISSUE TITLE
Tiếp tục training model

### ISSUE THREAD

**Issue by anhanhtdh01** [pbcquoc/vietocr#36]
hi anh !
Anh cho em hỏi là em muốn tiếp tục training model đang trên dở thì setup thế nào ạ ? Em đã thử truyền model vào checkpoint mà không được ???

**Comment by pbcquoc** [comment]
Hi e, tại vì lưu checkpoint khá nặng nên a ko hỗ trợ luôn ... e có thể train một lần cũng dc mà, a train 10m ảnh chỉ cần 3 ngày thôi.

**Comment by anhanhtdh01** [comment]
Dạ vâng anh ! tại em muốn thử các trường hợp thôi ạ ! Em cảm ơn anh ạ !
