### ISSUE TITLE
Hướng dẫn sử dụng model VGG19-bn - Seq2Seq	

### ISSUE THREAD

**Issue by chuyendq9x** [pbcquoc/vietocr#37]
Dear a Quốc,

Cho e hỏi a có model train của vgg_seq2seq và hướng dẫn dùng nó không. Em đang dùng vgg_transformer thấy nó đọc chậm thật

**Comment by anhanhtdh01** [comment]
bạn thay file config là đc mà

**Comment by chuyendq9x** [comment]
Mình thay được rồi nhưng mà thấy tốc độ nó cũng như vgg_transformer nhỉ. Bạn thấy chạy có nhanh hơn k.

**Comment by chuyendq9x** [comment]
Vấn đề nữa nếu có GPU thì để CUDA là 0 hay 1. nếu mình để 1 thì nó lỗi. 
RuntimeError: CUDA error: invalid device ordinal

**Comment by anhanhtdh01** [comment]
có nhiều GPU thì mới đặt là 1 nhé, 0 với 1 là chỉ số GPU đó bạn

**Comment by chuyendq9x** [comment]
> có nhiều GPU thì mới đặt là 1 nhé, 0 với 1 là chỉ số GPU đó bạn

Máy mình có 1 . mình đang đặt thế này, mỗi lần chạy 10s mới ra kết quả.
![image](https://user-images.githubusercontent.com/21030546/110925884-4e5bd780-8356-11eb-9021-e90e566a2eee.png)

**Comment by pbcquoc** [comment]
Hi bạn, không biết bạn tính thời gian dự đoán ntn?
Nhưng bạn chỉ cần load model một lần sau đó dùng model để dự đoán nhé. 
10s có vẻ như là thời gian load model của bạn luôn rồi.

**Comment by chuyendq9x** [comment]
![image](https://user-images.githubusercontent.com/21030546/110931220-95e56200-835c-11eb-9ddc-3ce94450fbdd.png)
vâng đúng rồi. lần nào e chạy cũng thế này. Vậy e viết như tnao để không load model nữa

**Comment by anhanhtdh01** [comment]
dòng 17 là predict đó bạn, đặt thời gian vào đó

**Comment by chuyendq9x** [comment]
ý mình là làm sao để lsau OCR không bị load model nữa. hay lần nào khởi tạo cũng pải load lâu như thế

**Comment by pbcquoc** [comment]
Hi @chuyendq9x , 
vấn đề của e là kĩ thuật lập trình, em cần load model ở đâu đó trước, 
sau đó khi có ảnh vào thì e sẽ lấy model ra để dự đoán. 
Nếu em có 1 ảnh thì tất nhiên là e cần load model trước, tuy nhiên nếu e có nhiều hơn 2 ảnh thì không cần thiết phải load lại model lần nữa mà chỉ gọi lại hàm predict nhé.

**Comment by chuyendq9x** [comment]
Ok a . em hiểu rồi. có cách nào load model nhanh hơn nữa không a

**Comment by pbcquoc** [comment]
Có vẻ như e cần tìm hiểu cách viết API, ví dụ như flask api python xem, mình sẽ start api và load model trong đó, để api đó chạy và khi nào có request cần dự đoán thì gọi api.
