### ISSUE TITLE
Một số vấn đề về mạng CNN

### ISSUE THREAD

**Issue by hisiter97** [pbcquoc/vietocr#38]
Em xin phép hỏi a một số vấn đề về mặt lý thuyết ạ.
- Mạng VGG-19 a sử dụng có đầu ra trước khi flatten là 1xCx2x32  tương ứng BxCxHxW1 (với ảnh đầu vào 128x32).  Khác với mã code của paper CRNN-CTC gốc là 1xCx1x33 ~ 33 timesteps.  Ý tưởng paper CRNN-CTC là mỗi timesteps sẽ tương ứng với một vùng chữ nhật widthx32 trên ảnh gốc, còn đầu ra của anh thì chiều height featuremap  không bằng 1 nên anh đã flatten để được 1xCx64 ~ 64 timesteps. Theo em thấy thì mỗi timestep trong 64 timestep kia chỉ biểu diễn được widthx16 trên ảnh gốc. Vậy tại sao anh lại thay đổi như vậy ?
- Vấn đề thứ hai là anh nghĩ sử dụng AvgPool2D thay vì Maxpool2D sẽ có lợi gì không ạ.
Em cảm ơn anh.

**Comment by pbcquoc** [comment]
Hi e, 
- Nếu 32 pixel width tương ứng với 1 timestep thì nhiều khả năng những chữ nhỏ hơn 32 pixel sẽ có khả năng không nhận dạng được, như dấu chấm, phẩy. 
- Còn height a không để bằng 1 vì a thấy thông tin theo chiều height giữ lại được chiều hơn khi đưa vào mô hình rnn ở bước kế tiếp, các chữ có dấu như â, ô. 
- Còn về AvgPool vs Maxpool, a nghĩ rằng e nên thử nghiệm để bik kết quả ak.

**Comment by hisiter97** [comment]
Vâng ạ, em cảm ơn anh

**Comment by hisiter97** [comment]
Vậy theo anh, có sự khác biệt giữa flatten feature map từ 3D thành 2D:  fx(h*w) (cách của anh) và (f*h)xw (cách của một số paper) không ạ. Ở đây chiều h = 2

**Comment by pbcquoc** [comment]
hi e, theo a biết thì CRNN flatten theo w và h, a không nghĩ là lại flatten theo fxh là hợp lý lắm.

**Comment by hisiter97** [comment]
vâng, e cảm ơn a đã phản hồi ạ
