### ISSUE TITLE
Performance khi deloy lên môi trường product

### ISSUE THREAD

**Issue by chuongnvk54** [pbcquoc/vietocr#39]
Hello a @pbcquoc,
Khi deloy lên môi trường production cụ thể là website và sử dụng kiến trúc Seq2Seq để predict, em nhận thấy time để predict khá lâu khoảng 3-4s. Có cách nào để improve k a?
E cảm ơn.

**Comment by pbcquoc** [comment]
a nghĩ là e đang chạy trên cpu thì mới lâu vậy ak. 
e nên chạy trên gpu cho nhanh ak .
