### ISSUE TITLE
error trong phần decode khi train

### ISSUE THREAD

**Issue by syanhcva** [pbcquoc/vietocr#40]
chào bạn, khi mình fine tune mô hình seq2seq thì gặp lỗi bên dưới, bạn có thể giải thích giúp mình được không

![image](https://user-images.githubusercontent.com/16000900/118260661-c5d7ef80-b4dc-11eb-9405-c15c2ccf65d6.png)

**Comment by syanhcva** [comment]
đây là config của mình:
![image](https://user-images.githubusercontent.com/16000900/118261064-40a10a80-b4dd-11eb-8d63-fd47ae297130.png)

**Comment by pbcquoc** [comment]
Hi, 
bạn tiền xử lý lại tập nhãn sao cho chỉ bao gồm các kí tự có trong tập vocab

**Comment by syanhcva** [comment]
thanks bạn, mình đã fix được rồi, do bộ gõ unicode trong tập nhãn của mình không đồng nhất
