### ISSUE TITLE
Error while training for new dataset?

### ISSUE THREAD

**Issue by thanhnguyentrung** [pbcquoc/vietocr#42]
When i tried to use your notebook and your dataset to train new model, i had an error "This DataLoader will create 3 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create". And when i set num_wokers = 2 in config file, it occured new error: "StopIteration".
Can you help me fix this error? Thank you!

**Comment by pbcquoc** [comment]
Hi, 
is your batch_size greater than the number of sample in your dataset?
please set config['batch_size'] = 8 #smaller batch_size if needed

**Comment by thanhnguyentrung** [comment]
> Hi,
> is your batch_size greater than the number of sample in your dataset?
> please set config['batch_size'] = 8 #smaller batch_size if needed
Thank you, this error is solved by your suggestion.
