### ISSUE TITLE
Điểm prob của vietocr

### ISSUE THREAD

**Issue by DucNguyen183** [pbcquoc/vietocr#43]
Hi anh, 
Em có sử dụng và fine tune lại Vietocr. Trong quá trình sử dụng thì em thấy prob trả về hầu như là 0.93. Sau khi fine tune thì prob trả về chủ yếu là 0.91. Anh cho em hỏi là cách tính prob của Vietocr như thế nào và tại sao prob trả về hầu như là giống nhau đến thế. Tks anh!

**Comment by pbcquoc** [comment]
Hi e, 
prob của câu a đơn giản là tính trung bình prob của các từ. 
do đó nếu có một vài kí tự sai thì kết quả prob cũng cao.
nếu mà model dự đoán đúng thì prob cao là bình thường mà....

**Comment by DucNguyen183** [comment]
thanks anh, vấn đề em hỏi là dù đúng hay sai thì lúc nào prob cũng ra ngang ngang nhau (0.93 với model gốc, ~ 0.91 với model sau khi mình fine tune). Em đã thử một vài model text recognition khác, thấy độ biến thiên của prob là khá cao.
ví dụ như ở repo https://github.com/JaidedAI/EasyOCR, range của prob từ khoảng 0.3 đến gần 1 (đây cũng là prob của riêng mô hình text recognition chứ không phải của cả flow ocr)

**Comment by pbcquoc** [comment]
Do cách cộng trung bình đó e. 
bên EasyOCR họ tính theo [custom mean](https://github.com/JaidedAI/EasyOCR/blob/ebc51fe33f2c3469dd4471141adc13b877c584a1/easyocr/recognition.py#L13).
