### ISSUE TITLE
Lỗi khi load model

### ISSUE THREAD

**Issue by andn2907** [pbcquoc/vietocr#44]
Em chào anh ạ, 
Em dùng version 0.3.5 và chạy theo hướng dẫn của anh. Đến bước khai báo "detector = Predictor(config)" thì em gặp lỗi: 
![image](https://user-images.githubusercontent.com/83748391/120734069-76507680-c512-11eb-9f5f-05671259cd50.png)
Em có thử thay bằng torch.jit.load() nhưng cũng không được, anh giúp em với ạ.

**Comment by pbcquoc** [comment]
Hi e, share code a xem thử nhé.

**Comment by andn2907** [comment]
Em gửi anh code ạ,
![image](https://user-images.githubusercontent.com/83748391/120750263-4617d080-c530-11eb-93f3-c9b4b17ace82.png)
![image](https://user-images.githubusercontent.com/83748391/120750318-5cbe2780-c530-11eb-811f-5c90c1767f68.png)
![image](https://user-images.githubusercontent.com/83748391/120750439-9000b680-c530-11eb-85cc-372e729205a4.png)

**Comment by pbcquoc** [comment]
hi e, e chạy trên hệ điều hành windows phải ko ?

**Comment by andn2907** [comment]
Em fix được rồi. Em cảm ơn anh ạ.
