### ISSUE TITLE
Lỗi ký tự '/'

### ISSUE THREAD

**Issue by nguyentrongnhat4869** [pbcquoc/vietocr#45]
Chào anh, em đang sử dụng vietocr để train lại trên tập dữ liệu của em. Tuy nhiên em nhận thấy rằng model chạy rất tốt trên hầu hết các loại chữ nhưng thường lỗi ở ký tự '/' như thông tin liên quan ngày tháng có '/' ở giữa. Cho em hỏi có cách nào để cải thiện vấn đề này k ạ! Em cảm ơn!

**Comment by pbcquoc** [comment]
Hi e, 
những kí tự nhỏ như '/' model rất hay bị miss, nếu em có bộ data của bài toán e đang làm thì hãy fintune model trên tập dữ liệu đó nhs.
