### ISSUE TITLE
Lỗi size mismatch

### ISSUE THREAD

**Issue by chauthehan** [pbcquoc/vietocr#47]
Em chào anh
Em đang train mô hình OCR sử dụng thư viện vietocr, em đã từng train vài lần trước đây nhưng hôm nay gặp một lỗi lạ, anh có thể giúp em xem đây là lỗi gì không ạ.
Em cảm ơn anh ạ.

Computing MD5: /tmp/tranformerorc.pth
MD5 matches: /tmp/tranformerorc.pth
transformer.decoder.embedding.weight missmatching shape, required torch.Size([256, 256]) but found torch.Size([233, 256])
transformer.decoder.fc_out.weight missmatching shape, required torch.Size([256, 1024]) but found torch.Size([233, 1024])
transformer.decoder.fc_out.bias missmatching shape, required torch.Size([256]) but found torch.Size([233])

**Comment by chauthehan** [comment]
đây là config của em

config = Cfg.load_config_from_name('vgg_seq2seq')
config['vocab'] = 'aAàÀảẢãÃáÁạẠăĂằẰẳẲẵẴắẮặẶâÂ ầẦẩẨẫẪấẤậẬbBcCdDđĐeEèÈẻẺẽẼéÉẹẸêÊềỀểỂễỄếẾệỆfFgGhHiIìÌỉỈĩĨíÍịỊjJkKlLmMnNoOòÒỏỎõÕóÓọỌôÔồỒổỔỗỖốỐộỘơƠờỜởỞỡỠớỚợỢpPqQrRsStTuUùÙủỦũŨúÚụỤưƯừỪửỬữỮứỨựỰvVwWxXyYỳỲỷỶỹỸýÝỵỴzZ0123456789#$%&()*+,-./:;<=>?@[]^`{|}~π→θ∂∫ΔλδφωΩ∞≈≠≤≥±┴∀∅⊄∈∄∃⊂⋂⊃∉'

dataset_params = {
    'name':'hw',
    'data_root':'.',
    'train_annotation':'train_line_annotation.txt',
    'valid_annotation':'test_line_annotation.txt'
}

params = {
         'print_every':200,
         'valid_every':5000,
          'iters':300000,
          'checkpoint':'./checkpoint/transformerocr_checkpoint.pth',    
          'export':'./weights/transformerocr.pth',
          'metrics': 10000

**Comment by pbcquoc** [comment]
hi e,
do tập vocab của e khác với tập default của thư viện nên nó báo vậy thôi. chứ model vẫn train bình thường chứ nhỉ ?
