### ISSUE TITLE
Traning with dual GPU

### ISSUE THREAD

**Issue by thienbui** [pbcquoc/vietocr#50]
Mình traning x2 RTX 3060 thì tham số "device" để như thế nào vậy Quốc?

Thanks.

**Comment by pbcquoc** [comment]
Hi, 
thư viện chưa support chạy nhiều gpu nha bạn.
với lại 1 gpu chạy cũng đủ nhanh rồi, bạn train tầm 1,2 ngày là sẽ hội tụ
