### ISSUE TITLE
How to get probability value when predict image??

### ISSUE THREAD

**Issue by phungtiep** [pbcquoc/vietocr#51]
Anh ơi, em muốn lấy được giá trị xác suất sau khi đọc ảnh xong thì mình lấy như nào ạ!

**Comment by pbcquoc** [comment]
Hi em, 
truyền ```return_prob=true``` nhé, prob được tính là trung bình cộng prob của các từ 
![image](https://user-images.githubusercontent.com/19279523/135979327-4441dadd-3901-455d-9b5d-c8fe18ae2b8f.png)

**Comment by phungtiep** [comment]
Vâng ạ, em cảm ơn anh nhiều ạ!
