### ISSUE TITLE
Kích thước đầu vào transformer

### ISSUE THREAD

**Issue by messithanh2k** [pbcquoc/vietocr#52]
Em chào anh và mọi người, em có thắc mắc cần mọi người giải đáp hộ ạ.
Như em từng đọc 1 bài làm áp dụng transformer cho câu văn bản thì đầu vào cho encoder cần padding để các câu có độ dài bằng nhau.
Nhưng em thấy ở đây, chiều rộng của ảnh đầu vào là khác nhau, sau lớp CNN thì kích thước input là W N C trong đó W khác nhau
Vậy nên anh và mọi ngườigiúp em rằng ở đây có cần padding để input có độ dài bằng nhau không ạ. Em cảm ơn ạ

**Comment by messithanh2k** [comment]
vâng em cảm ơn anh, anh cho em hỏi thêm là nếu kích thước các ảnh đầu vào trong 1 batch không bằng nhau thì có bị lỗi gì không ạ. Việc cho kích thước bằng nhau trong 1 batch có lợi ích gì ạ. Em cảm ơn anh

**Comment by pbcquoc** [comment]
'kích thước bằng nhau trong 1 batch có lợi ích gì ạ.' -> tránh lãng phí tài nguyên khi tính toán cho cả phần padding nha e, nên giúp train nhanh hơn

**Comment by messithanh2k** [comment]
vâng em cảm ơn anh ạ>
Còn 1 ý của em hỏi nữa là nếu kích thước các ảnh đầu vào trong 1 batch không bằng nhau thì có lỗi gì hay không ấy ạ.
Sorry anh tại em còn mông lung quá ấy ạ

**Comment by pbcquoc** [comment]
trong 1 batch mà kích thước ko bằng nhau thì ko train được (bug) thôi e :)

**Comment by messithanh2k** [comment]
anh cho em hỏi nốt được không ạ. Em padding cho tất cả ảnh bằng nhau rồi cho học hết, không xử lý phần không học padding. thì có được ko ạ
