### ISSUE TITLE
predict ra 1 kết quả

### ISSUE THREAD

**Issue by messithanh2k** [pbcquoc/vietocr#55]
sau khi em train với bộ dữ liệu của mình từ đầu, được file weights thì khi predict với ảnh nào cũng ra 1 kết quả duy nhất. 
Anh có thể giải thích giúp em và cách khắc phục ko ạ
Em cảm ơn anh

**Comment by pbcquoc** [comment]
về cơ bản thì e nói đúng rồi nhé. 
tuy nhiên lúc chạy thực tế a có resize các ảnh có kích thước gần giống nhau về cùng một kích cỡ. ví dụ như các ảnh có kích thước từ 300-> 309 pixel width sẽ được resize về cùng 300 pixel nếu mà vẫn ko đủ tạo thành một batch thì coi như bỏ qua.

**Comment by messithanh2k** [comment]
vâng em cảm ơn anh ạ
