### ISSUE TITLE
Cách train tiếp từ pretrained model cho 1 số ký tự chưa nhận diện được

### ISSUE THREAD

**Issue by nghetrung** [pbcquoc/vietocr#56]
Hi anh Quốc, 

Em có sử dụng VietOCR của anh và thấy model nhận diện rất tốt tất cả chữ cái và số. Tuy nhiên có 1 số ký tự đặc biệt mà model hoàn toàn không nhận diện được dù ảnh có rõ hay không (e.g. @)

Em có thử finetune mô hình bằng cách train tiếp từ pretrained model như anh đã hướng dẫn trong notebook với 1 tập ảnh chỉ có ký hiệu @. Em đã thử để "iter" cả nhỏ (20-100) lẫn lớn (>1000) tuy nhiên khi train xong mô hình dự đoán chỉ toàn @. 

Liệu có phải do việc train tiếp đã phá hủy các weights mà anh đã train từ trước không ạ? Nếu vậy thì em phải freeze các weights trước khi sử dụng hàm train của anh không ạ?

Em cảm ơn anh ạ

Note: em chỉ muốn train thêm @, không muốn cho thêm ảnh chữ vào vì model đã nhận diện rất tốt rồi.

**Comment by pbcquoc** [comment]
tập dataset của e bao nhiêu ảnh nhỉ?

**Comment by nghetrung** [comment]
e có khoảng 20 cái ảnh @ thôi ạ. Còn em có train thử thêm cả ảnh chữ lẫn @ thì khoảng 1k ảnh. Cả 2 cách đều kết quả không khả quan lắm ạ.

**Comment by pbcquoc** [comment]
vậy ít lắm e. e tăng lên 3k nhé. rồi set lr tầm 1e-4 hoặc nhỏ hơn

**Comment by nghetrung** [comment]
Vâng e thử lên 3k ảnh thì kết quả có khả quan hơn. 

Cho e hỏi là tại sao pretrained model của a khi dự đoán trên tập dữ liệu của e đã khá tốt rồi nhưng sao train tiếp nó lại tệ đi nếu có ít ảnh như vậy ạ?

**Comment by pbcquoc** [comment]
thì nó overfit tập train của e  thì cả tệ hơn. :)

**Comment by nghetrung** [comment]
Nếu vậy cứ khi nào muốn train thêm 1 ký tự nào đấy thì lại phải train lại cả các ký tự khác nữa ạ 😅. E thắc mắc mỗi đoạn đấy

**Comment by pbcquoc** [comment]
về cơ bản là thế nha e

**Comment by nghetrung** [comment]
Dạ vâng e cảm ơn a ạ :D
