### ISSUE TITLE
Suppress gdown print message

### ISSUE THREAD

**Issue by annguyenfoss** [pbcquoc/vietocr#59]
`return gdown.cached_download(url=url, path=cached, md5=md5, quiet=True)`

quiet=True chứ không phải quiet=quiet

Ref: https://github.com/wkentaro/gdown

Cheers

**Comment by annguyenfoss** [comment]
Sao đóng issue này mà không fix nhỉ?

**Comment by pbcquoc** [comment]
hi bạn, để tắt msg thì chỉ trong config, chứ ko cần phải sửa code đâu 
![image](https://user-images.githubusercontent.com/19279523/149471558-82bc85d6-89bc-4925-a66b-6df42022f2d4.png)
