### ISSUE TITLE
Model of ResNet in VietOCR

### ISSUE THREAD

**Issue by nguyenkhacduyngoc** [pbcquoc/vietocr#60]
Hi a,
Rất cảm ơn anh vì repo rất tuyệt ạ.
E có chút thắc mắc là trong code có ghi là Model ResNet 50 nhưng e thấy hình như ko phải vì custom block layer của R50 là [3, 4, 6, 3] nhưng của anh là  [1, 2, 5, 3]. Model này có cách infer hơi khác với ResNet, theo e tìm hiểu thì nó giống với model của Focusing attention Net (model có custom với 32 layers), code model thì e thấy giống của ClovaAi, e muốn hỏi để confirm lại ạ? K biết hiểu như vậy đúng chưa ạ.
2 nữa là performance của model trên CPU các dòn Xeon cực chậm ạ, có cách nào để giải quyết vấn đề này ko ạ (Infer trên các dòng CPU Core I thì bình thường ạ) Chậm hơn khoảng 10 -> 15 lần 
CPU Test: Xeon Gold 6450R.

**Comment by pbcquoc** [comment]
hi e, resnet thì e có thể custom theo ý e muốn, còn resnet được implement trong repo là a chôm về đó. 
performance trên cpu xeon thì a nghĩ là e kiểm tra xem lúc predict có chạy full các cores ko ? https://discuss.pytorch.org/t/bad-inference-performance-on-some-cpus/35539

**Comment by nguyenkhacduyngoc** [comment]
1. E hỏi thêm chút nữa với ạ, e có đổi sang ResNet gốc nhưng performance khá tệ (tệ hơn rất nhiều) so với ResNet kia (họ có custom để add thêm 1 vài block nhỏ sau mỗi layer (giống bài Focusing Attention Net). E đang chưa rõ nguyên nhân lắm (input_size của BiLSTM lúc này là 2048 + e dùng mô hình Attention OCR).
2. Ở repo của a thì đang sử dụng batch theo size ảnh, nhưng như vậy sẽ gặp vấn đề khi số lượng input theo size mà ko đủ 1 batch thì sẽ bị ignore hết. E dùng padding để resize về cùng 1 kích thước thì tránh đc trường hợp này. E muốn hỏi là a đã so sánh 2 cách làm này chưa ạ, và cách nào thì cho performance tốt hơn ạ.

**Comment by pbcquoc** [comment]
1. em kiểm tra lại stride size của 2 loại kiến trúc xem, ảnh đầu vào trong bài toán này thường dài và hẹp do đó stride size cần phải phù hợp. 
2. padding như e nói thì a chưa thử. chỗ này em có 2 trường hợp:
  2.1 cứ padding ảnh rồi input vào mô hình xem phần padding là ảnh bình thường
  2.2 hoặc là padding ảnh và chỉ cho mô hình biết để không optimize dự đoán cho phần padding này (giống như padding trong text, cách này cho kết quả tương tự như cách đang cài đặt).
 performance thì thử rồi mới biết nha e :))

**Comment by nguyenkhacduyngoc** [comment]
Tks anh ạ.
