### ISSUE TITLE
lỗi khi dùng pretrain để train với new data

### ISSUE THREAD

**Issue by Tomia1997** [pbcquoc/vietocr#63]
Em chào anh,
Em muốn dùng thư viện của a để finetuning lại với bộ dataset của em. 
Em thấy có options cho load pretrained model. Khi em để pretrained== True thì khi đến đoạn download pretrain model thì bị lỗi như trong ảnh.

![a](https://user-images.githubusercontent.com/100807219/156459005-31768087-b5de-4a44-81a8-6916e39f6e9e.png)

Em set pretrained = False  thì code chạy bình thường ạ.

Em đang dùng với vgg_transformer and đây là file config của em ạ.
![image](https://user-images.githubusercontent.com/100807219/156459210-0648ca91-90f9-4e1a-a52e-0b29164770ce.png)

Em xin cảm ơn

**Comment by PhamQuocHuy1101** [comment]
Google cần confirm, bạn chỉnh lại link model thêm phần "&confirm=t" (Ex: 'https://drive.google.com/uc?id=13327Y1tz1ohsm5YZMyXVMPIOjoOA0OaA&confirm=t')

**Comment by Tomia1997** [comment]
Thank @PhamQuocHuy1101 và  a @pbcquoc. Cả 2 cách đều được ạ.
