### ISSUE TITLE
Lỗi khi train model

### ISSUE THREAD

**Issue by DungNasSa10** [pbcquoc/vietocr#68]
MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant http://?

**Comment by DungNasSa10** [comment]
![Screenshot from 2022-05-12 23-19-49](https://user-images.githubusercontent.com/84455292/168123309-c81a1db1-589b-49e9-a1f7-f2f13fb80d1b.png)
![Screenshot from 2022-05-12 23-20-11](https://user-images.githubusercontent.com/84455292/168123316-57c59723-a136-4c34-9668-13e44c98f54a.png)
![Screenshot from 2022-05-12 23-20-26](https://user-images.githubusercontent.com/84455292/168123321-9d0449e9-45b8-4e1b-a4df-2f2e852389e5.png)

anh ơi cho em hỏi khi train model bị lỗi như này thì xử lí như nào ạ

**Comment by pbcquoc** [comment]
`pip install --upgrade vietocr`
nha e

**Comment by DungNasSa10** [comment]
![Screenshot from 2022-05-13 07-45-12](https://user-images.githubusercontent.com/84455292/168189700-6abceb5a-6caa-458f-a4d4-7e5716c4cf27.png)
![Screenshot from 2022-05-13 07-45-24](https://user-images.githubusercontent.com/84455292/168189703-fcbe2b85-9296-43ef-9eee-b19e4d292929.png)
![Screenshot from 2022-05-13 07-45-36](https://user-images.githubusercontent.com/84455292/168189704-6834dc13-9155-4647-8b92-0be8b0d3ae77.png)
![Screenshot from 2022-05-13 07-45-50](https://user-images.githubusercontent.com/84455292/168189706-56bcca46-e7b6-4831-8db1-e7ef5676a53f.png)
![Screenshot from 2022-05-13 07-45-56](https://user-images.githubusercontent.com/84455292/168189707-fc1fbf8f-56be-48d1-9edf-73c0af52b2df.png)
![Screenshot from 2022-05-13 07-46-06](https://user-images.githubusercontent.com/84455292/168189708-7c574564-7ff3-4dfd-9037-3ead5fbf3313.png)
![Screenshot from 2022-05-13 07-46-15](https://user-images.githubusercontent.com/84455292/168189710-3331a35c-30ff-4e00-82f8-1f191d11492c.png)

Sau khi upgrade lên gdown-4.4.0 vietocr-0.3.8 thì em lại gặp lỗi này ạ

**Comment by DungNasSa10** [comment]
Em cảm ơn anh em khắc phục được rồi ạ

**Comment by DungNasSa10** [comment]
Đã khắc phục khi upgrade vietocr=0.3.8
