### ISSUE TITLE
Lỗi khi trainer: TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

### ISSUE THREAD

**Issue by DungNasSa10** [pbcquoc/vietocr#69]

**Comment by DungNasSa10** [comment]
![Screenshot from 2022-05-15 16-19-03](https://user-images.githubusercontent.com/84455292/168465930-5ac0d52f-f521-4466-ba5d-9413846fc3fd.png)
![Screenshot from 2022-05-15 16-18-58](https://user-images.githubusercontent.com/84455292/168465936-d8430c60-ee94-4e84-92a1-8f159494b90e.png)
![Screenshot from 2022-05-15 16-16-48](https://user-images.githubusercontent.com/84455292/168465938-079023d3-2114-4115-8bfa-1ae265f182f4.png)
![Screenshot from 2022-05-15 16-16-23](https://user-images.githubusercontent.com/84455292/168465940-ac8bf5bc-631a-41a7-8ec1-5ba77f20e054.png)
![Screenshot from 2022-05-15 16-09-35](https://user-images.githubusercontent.com/84455292/168465942-a5a108fe-3ad9-44ab-9b35-79577c548d7a.png)

tập data em build như trong hướng dẫn nhưng khi train gặp lôi này anh em giúp em với ạ

**Comment by pbcquoc** [comment]
remove folder train_vietnamese rồi tạo lại dataset đi e. xem nó báo bug gì? lúc tạo nó in ra số mẫu đọc được. e check thử xem có đúng ko

**Comment by DungNasSa10** [comment]
em khắc phục được rồi cảm ơn anh nhiều

**Comment by DungNasSa10** [comment]
em xóa folder train_vietnamese khắc phục được rồi cảm ơn anh nhiều
