### ISSUE TITLE
Lỗi vi phạm requirement lmdb == 1.0.0

### ISSUE THREAD

**Issue by cloudmadeofcandy** [pbcquoc/vietocr#71]
Chào anh, khi em cài phiên bản VietOCR==0.3.5 (như được đề xuất trên https://pypi.org/project/vietocr/) thì gặp phải lỗi sau:
ERROR: Could not find a version that satisfies the requirement lmdb==1.0.0 (from vietocr) (from versions: 0.58, 0.59, 0.60, 0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.70, 0.71, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.80, 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.0.0, 1.1.0, 1.1.1, 1.2.0, 1.2.1, 1.3.0)
ERROR: No matching distribution found for lmdb==1.0.0.
(Text từ Windows Powershell, đã có quyền Admin)
Vấn đề là khi lmdb liệt kê các version, tồn tại 1.0.0.

Hiện em đang sử dụng Windows 11, phiên bản Python 3.9.7, sử dụng Conda
![image](https://user-images.githubusercontent.com/69132936/183841174-c0ab3914-35de-4d6a-a027-c9dfa94e2c28.png)

**Comment by cloudmadeofcandy** [comment]
Update: Hiện em đang cài patch-ng và Visual C++ 14.0 để thỏa mãn requirement của lmdb 1.0.0.

**Comment by cloudmadeofcandy** [comment]
Sau khi cài Visual C++ 14.0, em vẫn không thể cài lmdb 1.0.0. Hiện em xin đóng issue này lại, do đây là lỗi thuộc về C.

![image](https://user-images.githubusercontent.com/69132936/183844300-0e1b5d0f-156f-492b-a618-20df6339f6be.png)

**Comment by cloudmadeofcandy** [comment]
![image](https://user-images.githubusercontent.com/69132936/183848993-dd10ab3c-3cff-4746-bd3a-374522f17755.png)

**Comment by whoisltd** [comment]
bạn có thể thử giảm phiên bản python xuống thấp hơn 3.8 chẳng hạn coi dc không

**Comment by transybao1393** [comment]
Bạn thử chuyển từ == thành >= hoặc chọn 1 version phù hợp hơn trong stack install của nó gợi ý xem sao. 
Đôi khi cài dưới các version Python version khác nhau thì nó xảy ra tình trạng này hoặc đôi khi ngay cả các patch của python thay đổi thì cũng dẫn đến conflict

**Comment by cloudmadeofcandy** [comment]
Em tạo một venv mới chứa python == 3.9 thì nó chạy thành công. Em xin phép đóng issue này ạ
