### ISSUE TITLE
Về kiến trúc transformer

### ISSUE THREAD

**Issue by huytuong010101** [pbcquoc/vietocr#73]
Hi anh, cảm ơn anh vì đã chia sẽ repo hết sức bổ ích ạ. Đồng thời em củng có một vài thắc mắc hi vọng được anh giải đáp ạ.
- Anh có thể mô tả hàm loss của anh đang sử dụng được không ạ, E không thấy anh sử dụng CTCloss. Theo e hiểu thì CTCloss sẽ khắc phục được việc phải gắn nhãn vị trí nào ứng với ký tự nào bởi vì nó sẽ tính tất cả trường hợp có thể để tạo ra câu đã đánh nhãn.
- Theo như hình `https://pbcquoc.github.io/images/vietocr/transformerocr.jpg` thì trong 1 step nào đó input là `Nguyễn Đức` và Output là`Tuấn`. Làm sao mô hình có thể output 1 từ thay vì một kí tự như các mô hình OCR khác vậy ạ. Đối với các mô hình NLP thì mỗi embedding đại diện cho 1 từ thì có thể dễ hiểu, còn hiện tại input là embedding đại diện cho các cột của feature map thì chỗ này hơi khó hiểu ạ.
Em cảm ơn và hi vọng được a reply sớm ạ.

**Comment by pbcquoc** [comment]
Hi em, 
1. Kiến trúc seq2seq sử dụng crossentropy loss em nha. Khác với mô hình crnn sử dụng ctc loss nên em đừng nhầm lẫn 2 mô hình này.
2. Mô hình không output các từ bởi vì số lượng từ quá lớn. Các kí tự sẽ khả thi hơn em nhé.
Nếu input không phải là các cột của feature map thì em sẽ input thông tin ảnh vào mô hình transformer như thế nào nhỉ?

**Comment by huytuong010101** [comment]
Hi anh,
1. Nếu dùng crossentropy thì mình phải gán nhãn như thế nào anh nhỉ. E đang hình dung nếu dùng crossentropy thì ở mỗi step decode mình phải biết chính xác cần output kí tự nào, trong khi đó các nhãn OCR là full text của ảnh chứ không biết vị trí nào ứng với kí tự nào. Cái này dễ hiểu với CTCLoss vì CTCLoss sẽ tínhtất cả trường hợp có thể để tạo ra full text (nhãn)
2. Okey anh do cái ảnh làm em tưởng ở mỗi lần decode nó cho ra 1 từ.

**Comment by huytuong010101** [comment]
![image](https://user-images.githubusercontent.com/53045632/193399261-e4f1202d-e763-42cd-bfbd-7b095961e3fc.png)
ủa sao chỗ này anh bảo output từng từ nhỉ :3

**Comment by pbcquoc** [comment]
Thế thì để a sửa lại haha

**Comment by pbcquoc** [comment]
Em còn câu hỏi gì nữa không nhỉ?

**Comment by huytuong010101** [comment]
e còn câu này hình như a chưa trả lời ấy ạ
```
Nếu dùng crossentropy thì mình phải gán nhãn như thế nào anh nhỉ. E đang hình dung nếu dùng crossentropy thì ở mỗi step decode mình phải biết chính xác cần output kí tự nào, trong khi đó các nhãn OCR là full text của ảnh chứ không biết vị trí nào ứng với kí tự nào. Cái này dễ hiểu với CTCLoss vì CTCLoss sẽ tính tất cả trường hợp có thể để tạo ra full text (nhãn)
```

**Comment by pbcquoc** [comment]
với transformerOCR, mình không cần biết thiết phải biết vị trí kí tự đó. Chỉ cần mỗi step của decoder mình dự đoán một kí tự là được vì kiến trúc của mô hình cho phép làm điều đó. Em xem lại thử nhé.

**Comment by huytuong010101** [comment]
dạ vâng e cảm ơn anh, để e tìm hiểu thêm ạ
