### ISSUE TITLE
Error local variable 'prob' referenced before assignment khi save export: './weights/transformerocr.pth'

### ISSUE THREAD

**Issue by sangnv3007** [pbcquoc/vietocr#74]
Chào a, e training mô hình đến bước export ra model thì gặp lỗi này. Rất mong a có thể giải đáp giúp e ạ. 
Cảm ơn và chúc a nhiều sức khoẻ !
![image](https://user-images.githubusercontent.com/80217001/194681686-e26e786e-ef9f-4a68-b2e4-11310abe74ed.png)
![image](https://user-images.githubusercontent.com/80217001/194681461-bc87f49c-f3b1-4e72-a44b-8118524183a4.png)

**Comment by pbcquoc** [comment]
Tập validation ít mẫu hoặc em không có tập validation nhé.

**Comment by sangnv3007** [comment]
Dạ số mẫu validation ít nhất đủ để training là khoảng bao nhiêu ạ nhỉ?

**Comment by pbcquoc** [comment]
lớn hơn batch_size em đang để nhé.

**Comment by sangnv3007** [comment]
Dạ vâng e fix được rùi ạ, cảm ơn a rất nhiềuuu ạ <3
