### ISSUE TITLE
Can't load resnet_transformer config : Keywords must be a string

### ISSUE THREAD

**Issue by TrinhThiBaoAnh** [pbcquoc/vietocr#75]
![Untitled](https://user-images.githubusercontent.com/96029534/194834807-0f8572e3-d2f2-4705-955e-50baff3f3a82.png)
I run successfully with vgg_transformer and vgg_seq2seq but when I try resnet_transformer and other ones, it does not work and throw this error. I still don't know why this happens?

**Comment by pbcquoc** [comment]
other configurations wasn't implemented, so pls use only vgg_transformer and vgg_seq2seq.

**Comment by TrinhThiBaoAnh** [comment]
Oke, thanks bro
