### ISSUE TITLE
lỗi data huấn luyện

### ISSUE THREAD

**Issue by nhathoang0110** [pbcquoc/vietocr#76]
Em chào a ạ. Em có sử dụng finetune trên dữ liệu của mình, Em có dùng visualize dữ liệu thì thấy có một vài kí tự nó decocde thành * như sau thì có vấn đề gì không ạ ? Em check trên dữ liệu của mình thì nằm trong vocab cả rồi.
![image](https://user-images.githubusercontent.com/55668910/196689351-d7e63afb-c08d-40b0-97ca-7f4d6ca75f19.png)

**Comment by nhathoang0110** [comment]
![image](https://user-images.githubusercontent.com/55668910/196689445-17598b75-f4ff-40d7-84de-43b420994eda.png)

**Comment by pbcquoc** [comment]
bình thường e nhé, đó là data enhancement thôi.
