### ISSUE TITLE
Lỗi khi pretrain mô hình

### ISSUE THREAD

**Issue by haianhaff** [pbcquoc/vietocr#77]
![image](https://user-images.githubusercontent.com/119098037/204077087-c5b61afd-6797-4282-9ef3-aff3fa907351.png)
Em chào anh, em thử update vietocr nhưng vẫn gặp lỗi này ạ

**Comment by pbcquoc** [comment]
Hi em,
Anh đang fix nhé. 
Em tạm thời tải weight xuống bằng trình duyệt và update lên vietocr==0.3.10
rồi đổi config như này nhé. 
config['pretrain'] = {'id_or_url':'path/to/weight.pth'}

**Comment by pbcquoc** [comment]
pip install vietocr==0.3.11
để upgrade lên version mới nhất đã được fix bug download nhé em.
