### ISSUE TITLE
Couldn't download the weights for vietocr config 

### ISSUE THREAD

**Issue by rama298** [pbcquoc/vietocr#79]
![image](https://user-images.githubusercontent.com/115778829/204245620-a009cc59-13d8-4205-b8df-0761275d505a.png)
![image](https://user-images.githubusercontent.com/115778829/204245717-c65ee029-f9b8-4d83-92cb-687c470c04a5.png)
Tried with Gpu and with out Gpu , Tried with downloading the weights file 

Cant able to resolve this error

Can someone help with this

**Comment by tsdocode** [comment]
I have faced the same issue. Perhaps the author changed the permissions on the weight file. However, you can manually download the weight and configure it with a file path rather than a Google Drive link.

`config['weights'] = 'transformerocr.pth`

**Comment by pbcquoc** [comment]
Hi, 
lỗi gdown @rama298, mình đang fix.

**Comment by rama298** [comment]
Its working now Thanks!

**Comment by rama298** [comment]
Hi @pbcquoc its giving the same error, I download the weight and specified the path also

**Comment by pbcquoc** [comment]
Hi @tsdocode ,
Pls provide error log here.

**Comment by rama298** [comment]
![image](https://user-images.githubusercontent.com/115778829/205242269-9426262c-944b-483b-9153-20f87a96693d.png)

**Comment by pbcquoc** [comment]
Hi @rama298 
pip install vietocr==0.3.11
để upgrade lên version mới nhất đã được fix bug download nhé!.

**Comment by rama298** [comment]
When I try to implement in my local system I am facing this error 
![image](https://user-images.githubusercontent.com/115778829/205564346-6375e064-3c27-4ea7-8513-7e79e30ffedb.png)

**Comment by pbcquoc** [comment]
bạn thử download xem có được file này không nhé! 
https://vocr.vn/data/vietocr/config/base.yml

**Comment by rama298** [comment]
Nope couldn't download the file 

![image](https://user-images.githubusercontent.com/115778829/205594606-6a613523-a1e7-46ae-9e5d-1e851b358aeb.png)
