### ISSUE TITLE
How can I train the vietocr for Real time Hand written text recognition 

### ISSUE THREAD

**Issue by rama298** [pbcquoc/vietocr#81]
I have a use case where need to recognize the hand written text from the document but its not showing good results. It is working for printed text.

So How can I train the vietocr for hand written text 
![37](https://user-images.githubusercontent.com/115778829/204534596-5beafb4a-4cc4-4ddf-b26b-8cd425077ca7.png)
![content14](https://user-images.githubusercontent.com/115778829/204534631-192d6797-1ace-487f-8780-ac488c2c6863.png)
 
These are my sample hand written text images

**Comment by pbcquoc** [comment]
Hi @rama298 ,
Model was trained on the printed dataset so it won't work for handwritten data.
You should finetune model on your handwrittern data before using it.

**Comment by rama298** [comment]
Can I retrain the vietocr with hand written data will it work!!

**Comment by pbcquoc** [comment]
It will able to regconize handwittern dataset.
