### ISSUE TITLE
Couldn't load latest version properly giving SSLError 

### ISSUE THREAD

**Issue by rama298** [pbcquoc/vietocr#82]
https://github.com/pbcquoc/vietocr/issues/79#issuecomment-1336027208

I am facing SSLERROR in my local system  while running the code 

It's not able to access the base.yml file 

![image](https://user-images.githubusercontent.com/115778829/205564965-a9833516-9036-4105-8b50-9b5bc88fd656.png)

**Comment by rama298** [comment]
https://github.com/pbcquoc/vietocr/issues/79#issuecomment-1336974208

**Comment by pbcquoc** [comment]
try to run your code on colab to see whether it shows the error or not?since i can't replicate your bug on my side.

**Comment by rama298** [comment]
In colab I can able- to import the config but getting this error while initiating the Trainer 
![image](https://user-images.githubusercontent.com/115778829/205925369-76a2633f-eb42-455b-97af-9a837e86bebc.png)

**Comment by rama298** [comment]
I solved the SSLERROR 

I think there are lots of bugs in code in different environments its giving different errors

I ran the code in my local system  and I am getting this error why I trying to train it 

![image](https://user-images.githubusercontent.com/115778829/206121874-cb35047f-1ad0-4196-bffc-39fc74995977.png)

**Comment by pbcquoc** [comment]
update to the lastest version vocr==0.3.11

**Comment by rama298** [comment]
Tried with latest version

![image](https://user-images.githubusercontent.com/115778829/206178378-c2f66d5f-4a09-49c2-885d-d0fef9117f41.png)

**Comment by rama298** [comment]
Hi 

Again the SSL Error is coming previously I opened the vscode with administration access and it worked but now with Administration access also its showing the SSL Error

I installed the latest version only 

![image](https://user-images.githubusercontent.com/115778829/206653798-d85dbd24-23d1-4ab2-b5a6-029c1563f809.png)

**Comment by pbcquoc** [comment]
try to run this code in Linux
