### ISSUE TITLE
Lỗi download weight khi huấn luyện

### ISSUE THREAD

**Issue by nhathoang0110** [pbcquoc/vietocr#90]
Em chào anh. Em có huấn luyện mô hình seq2seq thì gặp lỗi sau :
TypeError: download_weights() argument after ** must be a mapping, not str.
Nhờ anh chỉ cho cách fix ạ. Em cảm ơn
<img width="746" alt="Screenshot 2023-02-08 at 11 17 54" src="https://user-images.githubusercontent.com/55668910/217432355-883f474f-e776-4bd1-90e8-5bcd13a98a65.png">

**Comment by pbcquoc** [comment]
cập  nhật lên latest version đi e

**Comment by nhathoang0110** [comment]
em lại đang dùng bằng clone github để chỉnh sửa 1 vài chỗ. Chưa cập nhật ở source github hả a? vì em đã clone lại rồi

**Comment by pbcquoc** [comment]
pull code mới nhất về là được e nha

**Comment by pbcquoc** [comment]
e fix được chưa nhỉ ?

**Comment by nhathoang0110** [comment]
em fix đc rồi em cảm ơn ạ. Anh cho em hỏi thêm là có cách nào có thể giúp tăng tốc độ của mô hình khi muốn chạy product không ạ ?

**Comment by pbcquoc** [comment]
Hi em,

**Comment by ngochoai2001** [comment]
a ơi em đang ở rev mới nhất, nhưng cũng bị lỗi tương tự ạ
![image](https://github.com/pbcquoc/vietocr/assets/60635339/bdf6e236-597f-4b79-a495-57e2562602d0)

e thấy đoạn này là trả về 1 str (url) chứ nó không có trả về 1 dict ạ, còn trong file yml thì lại khác ạ 
![image](https://github.com/pbcquoc/vietocr/assets/60635339/4fa97475-489d-4dc3-bc2d-b5c43abefdb4)

**Comment by ngochoai2001** [comment]
em đã pull code mới nhất về rồi nhưng nó vẫn bị lỗi trên ạ
![image](https://github.com/pbcquoc/vietocr/assets/60635339/19ceca28-e8bc-4707-bae3-18634b48b96b)
trên link raw thì e thấy pretrain nó trả về 1 url (str)
trên file yml thì trả về 1 dict 
![image](https://github.com/pbcquoc/vietocr/assets/60635339/62cd31d3-50ac-4b95-ae74-4dfdb3290ced)
mà lúc e dùng load form file thì nó không load được base config ý ạ

**Comment by pbcquoc** [comment]
Hi em, 

sau khi e load được file config và train được với file config đó. thì lưu lại file config bằng hàm save('file_name'), rồi hãy load lại bằng load_from_file nhé.

**Comment by ngochoai2001** [comment]
e debug thì file config được load từ link raw.github kia về ý ạ
=> config['pretrain'] nó trả về 1 url chứ không phải là một dict ý a
thế nên em bị lỗi  "** after must be mapping, not str" ý ạ

**Comment by ngochoai2001** [comment]
e dùng trực tiếp code của github chứ không pip install vietocr ạ

**Comment by pbcquoc** [comment]
e pull code mới nhất về chưa ?

**Comment by ngochoai2001** [comment]
ôi e check thì phát hiện code của e clone từ link https://github.com/bangnghh/vietocr này về ạ
nên rev mới nhất vẫn là bản cũ của anh ạ
e cảm ơn anh ạ
