### ISSUE TITLE
e

### ISSUE THREAD

**Issue by htvh** [pbcquoc/vietocr#91]
![image](https://user-images.githubusercontent.com/125939423/220232557-a3e7d1b4-cce9-43c6-b2ad-0eba87031a72.png)
cho em hỏi cách fix lỗi này vs ạ

**Comment by pbcquoc** [comment]
Tập nhãn của e bị lỗi rồi.

**Comment by htvh** [comment]
cho em hỏi em ko tải nó trực tiếp trong code mà copy link để tại v liệu nó
có sinh ra lỗi k ạ

Vào CN, 5 thg 3, 2023 vào lúc 10:46 Pham Ba Cuong Quoc <
***@***.***> đã viết:
