### ISSUE TITLE
Key error trong lúc train

### ISSUE THREAD

**Issue by Syun1208** [pbcquoc/vietocr#92]
Dạ em chào anh, anh xem giúp em cái bug này với ạ
![image](https://user-images.githubusercontent.com/86679402/220242188-913ecc71-07f3-4e87-89c9-2fe2cc457769.png)

![image](https://user-images.githubusercontent.com/86679402/220241925-335130ea-a90b-4a6a-99b7-6ffb8d2a9cd1.png)

![image](https://user-images.githubusercontent.com/86679402/220241988-07f44ce9-c219-4799-a1b5-d2056d11c49e.png)

**Comment by pbcquoc** [comment]
Hi em, 
Kí tự gây lỗi keyerror không nằm trong tập từ vựng, 
Em cần tiền xử lý tập nhãn hoặc bổ sung kí tự đó vào tập vocab nhé.
